USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS FSI_PAYMENTS DATA_RETENTION_TIME_IN_DAYS = 7 COMMENT = 'Cross-Border Payment Processing & Settlement — Singapore FSI Demo';
CREATE SCHEMA IF NOT EXISTS FSI_PAYMENTS.RAW DATA_RETENTION_TIME_IN_DAYS = 3;
CREATE SCHEMA IF NOT EXISTS FSI_PAYMENTS.CURATED DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS FSI_PAYMENTS.AI DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS FSI_PAYMENTS.APP;

CREATE WAREHOUSE IF NOT EXISTS WH_PAYMENTS WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
