USE ROLE ACCOUNTADMIN;
USE DATABASE FSI_PAYMENTS;
USE SCHEMA RAW;
USE WAREHOUSE WH_PAYMENTS;

CREATE STORAGE INTEGRATION IF NOT EXISTS FSI_DEMOS_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE STORAGE_PROVIDER = 'S3' ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::__AWS_ACCOUNT_ID__:role/snowflake-fsi-demos-s3-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://sg-fsi-demos-2026/');

CREATE STAGE IF NOT EXISTS FSI_PAYMENTS.RAW.PAYMENTS_S3_STAGE
    URL = 's3://sg-fsi-demos-2026/payments/'
    STORAGE_INTEGRATION = FSI_DEMOS_S3_INTEGRATION
    FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE);

CREATE NETWORK RULE IF NOT EXISTS FSI_PAYMENTS.AI.BEDROCK_NETWORK_RULE
    TYPE = HOST_PORT MODE = EGRESS VALUE_LIST = ('bedrock-runtime.us-west-2.amazonaws.com:443');

CREATE SECRET IF NOT EXISTS FSI_PAYMENTS.AI.BEDROCK_SECRET
    TYPE = GENERIC_STRING SECRET_STRING = '{}';

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS FSI_PAYMENTS_BEDROCK_EAI
    ALLOWED_NETWORK_RULES = (FSI_PAYMENTS.AI.BEDROCK_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (FSI_PAYMENTS.AI.BEDROCK_SECRET)
    ENABLED = TRUE;
