USE ROLE ACCOUNTADMIN;
USE DATABASE FSI_PAYMENTS;
USE SCHEMA RAW;
USE WAREHOUSE WH_PAYMENTS;

CREATE TABLE IF NOT EXISTS PAYMENTS_RAW (
    PAYMENT_ID STRING NOT NULL, SENDER_BANK STRING, RECEIVER_BANK STRING,
    SENDER_ACCOUNT STRING, RECEIVER_ACCOUNT STRING, AMOUNT NUMBER(18,2),
    CURRENCY STRING, AMOUNT_SGD NUMBER(18,2), PAYMENT_TYPE STRING,
    CORRIDOR STRING, REFERENCE STRING, INITIATED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SETTLEMENTS_RAW (
    SETTLEMENT_ID STRING NOT NULL, PAYMENT_ID STRING, CLEARING_SYSTEM STRING,
    STATUS STRING, SETTLED_AT TIMESTAMP_NTZ, SETTLEMENT_AMOUNT NUMBER(18,2),
    FEES NUMBER(18,4), FAILURE_REASON STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FX_RATES_RAW (
    RATE_ID STRING NOT NULL, CURRENCY_PAIR STRING,
    BID_RATE NUMBER(18,6), ASK_RATE NUMBER(18,6), MID_RATE NUMBER(18,6),
    RATE_TS TIMESTAMP_NTZ, LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EXCEPTIONS_RAW (
    EXCEPTION_ID STRING NOT NULL, PAYMENT_ID STRING, EXCEPTION_TYPE STRING,
    SEVERITY STRING, DETAILS STRING, STATUS STRING DEFAULT 'OPEN',
    RESOLUTION STRING, RAISED_AT TIMESTAMP_NTZ, RESOLVED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
