-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT route.ID AS ENTITY_ID, route.NAME AS ENTITY_NAME,
       route.REGION, route.CATEGORY, route.RISK_TIER, route.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.PAYMENT_COUNT) AS PAYMENT_COUNT,
       SUM(observation.VALUE_SGD) AS VALUE_SGD,
       SUM(observation.EXCEPTION_COUNT) AS EXCEPTION_COUNT,
       SUM(observation.FAILED_COUNT) AS FAILED_COUNT,
       SUM(observation.SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(observation.RECON_DUE) AS RECON_DUE,
       SUM(observation.RECON_COMPLETED) AS RECON_COMPLETED,
       100.0 * (SUM(observation.PAYMENT_COUNT) - SUM(observation.EXCEPTION_COUNT)) / NULLIF(SUM(observation.PAYMENT_COUNT), 0) AS STP_RATE_PCT,
       100.0 * SUM(observation.FAILED_COUNT) / NULLIF(SUM(observation.EXCEPTION_COUNT), 0) AS EXCEPTION_FAILURE_PCT,
       100.0 * SUM(observation.RECON_COMPLETED) / NULLIF(SUM(observation.RECON_DUE), 0) AS RECON_COMPLIANCE_PCT,
       AVG(observation.SCREENING_HIT_PCT) AS AVG_SCREENING_HIT_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.ROUTE_DAILY observation
JOIN RAW.ROUTES route ON route.ID = observation.ENTITY_ID
GROUP BY route.ID, route.NAME, route.REGION, route.CATEGORY, route.RISK_TIER, route.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(PAYMENT_COUNT) AS PAYMENT_COUNT, SUM(VALUE_SGD) AS VALUE_SGD,
       SUM(EXCEPTION_COUNT) AS EXCEPTION_COUNT, SUM(FAILED_COUNT) AS FAILED_COUNT,
       100.0 * SUM(FAILED_COUNT) / NULLIF(SUM(EXCEPTION_COUNT), 0) AS EXCEPTION_FAILURE_PCT
FROM RAW.ROUTE_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.EXCEPTION_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EXCEPTION_TYPE, SUM(EXCEPTION_COUNT) AS EXCEPTION_COUNT,
       SUM(FAILED_COUNT) AS FAILED_COUNT,
       SUM(SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(VALUE_SGD) AS EXPOSED_VALUE_SGD,
       100.0 * SUM(FAILED_COUNT) / NULLIF(SUM(EXCEPTION_COUNT), 0) AS EXCEPTION_FAILURE_PCT
FROM RAW.ROUTE_DAILY
WHERE EXCEPTION_COUNT > 0
GROUP BY EXCEPTION_TYPE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(PAYMENT_COUNT) AS PAYMENTS, SUM(EXCEPTION_COUNT) AS EXCEPTIONS,
         SUM(FAILED_COUNT) AS FAILED, SUM(SLA_BREACHED) AS BREACHES, SUM(VALUE_SGD) AS VALUE_SGD,
         SUM(RECON_DUE) AS RECON_DUE, SUM(RECON_COMPLETED) AS RECON_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.ROUTE_DAILY
), book AS (SELECT COUNT(*) AS ROUTE_COUNT FROM RAW.ROUTES),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.DUE_DILIGENCE_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Straight-Through Rate' AS TITLE,
         100.0 * (PAYMENTS - EXCEPTIONS) / NULLIF(PAYMENTS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Exceptions Raised', EXCEPTIONS, '' FROM observations
  UNION ALL SELECT 3, 'Failed Payments', FAILED, '' FROM observations
  UNION ALL SELECT 4, 'Exception Failure Rate', 100.0 * FAILED / NULLIF(EXCEPTIONS, 0), '%' FROM observations
  UNION ALL SELECT 5, 'SLA Breaches', BREACHES, '' FROM observations
  UNION ALL SELECT 6, 'Value Processed (SGD M)', VALUE_SGD / 1e6, '' FROM observations
  UNION ALL SELECT 7, 'Payments Processed', PAYMENTS, '' FROM observations
  UNION ALL SELECT 8, 'Nostro Reconciliation Compliance', 100.0 * RECON_COMPLETED / NULLIF(RECON_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Routes Monitored', ROUTE_COUNT, '' FROM book
  UNION ALL SELECT 10, 'Due Diligence Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Due Diligence Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                WHEN metrics.SORT_ORDER = 1 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 2), '990.00'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.EXCEPTION_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
