-- Payment-failure risk scoring and exception-volume forecast over the synthetic snapshot.
-- Predicts P(failed payment on the route in the next 7 days) per route and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.FAILURE_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, a.CATEGORY, a.RISK_TIER, a.ROUTE_AGE_YEARS,
       r.SCREENING_HIT_PCT, r.AVG_SETTLE_MIN,
       AVG(r.SCREENING_HIT_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS SCREENING_HIT_7D,
       SUM(r.FAILED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS FAILED_30D,
       IFF(SUM(r.FAILED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'FAILURE', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.ROUTE_DAILY r JOIN RAW.ROUTES a ON a.ID = r.ENTITY_ID
-- Corridor-wide clearing outages are not route-driven, so they are excluded from training.
WHERE r.EXCEPTION_TYPE <> 'Clearing system outage';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.FAILURE_TRAIN AS
SELECT CATEGORY, RISK_TIER, ROUTE_AGE_YEARS, SCREENING_HIT_PCT, AVG_SETTLE_MIN, SCREENING_HIT_7D, FAILED_30D, LABEL
FROM ML.FAILURE_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.FAILURE_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, RISK_TIER, ROUTE_AGE_YEARS, SCREENING_HIT_PCT, AVG_SETTLE_MIN, SCREENING_HIT_7D, FAILED_30D, LABEL
FROM ML.FAILURE_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.FAILURE_RISK_MODEL(
  INPUT_DATA => TABLE(ML.FAILURE_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.FAILURE_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.FAILURE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'ROUTE_AGE_YEARS', ROUTE_AGE_YEARS,
           'SCREENING_HIT_PCT', SCREENING_HIT_PCT, 'AVG_SETTLE_MIN', AVG_SETTLE_MIN,
           'SCREENING_HIT_7D', SCREENING_HIT_7D, 'FAILED_30D', FAILED_30D)):probability:FAILURE::FLOAT AS P
  FROM ML.FAILURE_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'FAILURE', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'FAILURE', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'FAILURE', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'FAILURE', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per route (label unknown, so excluded from features).
CREATE TABLE ML.FAILURE_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.FAILURE_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.FAILURE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'ROUTE_AGE_YEARS', ROUTE_AGE_YEARS,
           'SCREENING_HIT_PCT', SCREENING_HIT_PCT, 'AVG_SETTLE_MIN', AVG_SETTLE_MIN,
           'SCREENING_HIT_7D', SCREENING_HIT_7D, 'FAILED_30D', FAILED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:FAILURE::FLOAT, 4) AS FAILURE_PROB_7D,
       CASE WHEN P:probability:FAILURE::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:FAILURE::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Hub-wide exception-volume forecast (14 days) from the daily series, for operations staffing.
CREATE VIEW ML.DAILY_EXCEPTIONS AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(EXCEPTION_COUNT)::FLOAT AS EXCEPTION_COUNT
FROM RAW.ROUTE_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.EXCEPTION_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_EXCEPTIONS),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'EXCEPTION_COUNT'
);

CREATE TABLE ML.EXCEPTION_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS EXCEPTION_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.EXCEPTION_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
